torchrun --nproc_per_node 8 -m training.main \
    --train-data /home/jeffliang/zsseg/datasets/coco/meta/coco_merge_nouns_mIoU27_deduplicated.csv \
    --train-num-samples 442117 \
    --lr 0.000005 \
    --warmup 100 \
    --force-quick-gelu \
    --dataset-type csv \
    --batch-size 32 \
    --precision amp \
    --workers 4 \
    --model  ViT-L-14 \
    --lock-text \
    --zeroshot-frequency 1 \
    --save-frequency 1 \
    --epoch 5 \
    --pretrained  openai \
    --imagenet-val /home/jeffliang/zsseg/datasets/ADEChallengeData2016/images/validation_mask