torchrun --nproc_per_node 8 -m training.main \
    --train-data /home/jeffliang/zsseg/datasets/coco/meta/cocostuff171_mask_train.csv \
    --train-num-samples 965035 \
    --lr 0.00002 \
    --warmup 100 \
    --force-quick-gelu \
    --dataset-type csv \
    --batch-size 128 \
    --precision amp \
    --workers 4 \
    --model  ViT-B-16 \
    --lock-text \
    --lock-image \
    --lock-image-unlocked-groups 3 \
    --zeroshot-frequency 1 \
    --save-frequency 1 \
    --epoch 10 \
    --pretrained  openai \
    --imagenet-val /home/jeffliang/zsseg/datasets/ADEChallengeData2016/images/validation_mask
