

ade150_classnames = ['wall', 'building', 'sky', 'floor', 'tree', 'ceiling', 'road, route', 'bed', 'window', 'grass', 'cabinet', 'sidewalk, pavement', 'person', 'earth, ground', 'door', 'table', 'mountain, mount', 'plant', 'curtain', 'chair', 'car', 'water', 'painting, picture', 'sofa', 'shelf', 'house', 'sea', 'mirror', 'rug', 'field', 'armchair', 'seat', 'fence', 'desk', 'rock, stone', 'wardrobe, closet, press', 'lamp', 'tub', 'rail', 'cushion', 'base, pedestal, stand', 'box', 'column, pillar', 'signboard, sign', 'chest of drawers, chest, bureau, dresser', 'counter', 'sand', 'sink', 'skyscraper', 'fireplace', 'refrigerator, icebox', 'grandstand, covered stand', 'path', 'stairs', 'runway', 'case, display case, showcase, vitrine', 'pool table, billiard table, snooker table', 'pillow', 'screen door, screen', 'stairway, staircase', 'river', 'bridge, span', 'bookcase', 'blind, screen', 'coffee table', 'toilet, can, commode, crapper, pot, potty, stool, throne', 'flower', 'book', 'hill', 'bench', 'countertop', 'stove', 'palm, palm tree', 'kitchen island', 'computer', 'swivel chair', 'boat', 'bar', 'arcade machine', 'hovel, hut, hutch, shack, shanty', 'bus', 'towel', 'light', 'truck', 'tower', 'chandelier', 'awning, sunshade, sunblind', 'street lamp', 'booth', 'tv', 'plane', 'dirt track', 'clothes', 'pole', 'land, ground, soil', 'bannister, banister, balustrade, balusters, handrail', 'escalator, moving staircase, moving stairway', 'ottoman, pouf, pouffe, puff, hassock', 'bottle', 'buffet, counter, sideboard', 'poster, posting, placard, notice, bill, card', 'stage', 'van', 'ship', 'fountain', 'conveyer belt, conveyor belt, conveyer, conveyor, transporter', 'canopy', 'washer, automatic washer, washing machine', 'plaything, toy', 'pool', 'stool', 'barrel, cask', 'basket, handbasket', 'falls', 'tent', 'bag', 'minibike, motorbike', 'cradle', 'oven', 'ball', 'food, solid food', 'step, stair', 'tank, storage tank', 'trade name', 'microwave', 'pot', 'animal', 'bicycle', 'lake', 'dishwasher', 'screen', 'blanket, cover', 'sculpture', 'hood, exhaust hood', 'sconce', 'vase', 'traffic light', 'tray', 'trash can', 'fan', 'pier', 'crt screen', 'plate', 'monitor', 'bulletin board', 'shower', 'radiator', 'glass, drinking glass', 'clock', 'flag']

openai_imagenet_template = [
    lambda c: f"a photo of a {c}.",
    lambda c: f"This is a photo of a {c}",
    lambda c: f"There is a {c} in the scene",
    lambda c: f"There is the {c} in the scene",
    lambda c: f"a photo of a {c} in the scene",
    lambda c: f"a photo of a small {c}.",
    lambda c: f"a photo of a medium {c}.",
    lambda c: f"a photo of a large {c}.",
    lambda c: f"This is a photo of a small {c}.",
    lambda c: f"This is a photo of a medium {c}.",
    lambda c: f"This is a photo of a large {c}.",
    lambda c: f"There is a small {c} in the scene.",
    lambda c: f"There is a medium {c} in the scene.",
    lambda c: f"There is a large {c} in the scene.",
    ]

# openai_imagenet_template = [
#     lambda c: f"a photo of a {c}.",
#     lambda c: f"This is a photo of a {c}",
#     lambda c: f"There is a {c} in the scene",
#     lambda c: f"There is the {c} in the scene",
#     lambda c: f"a photo of a {c} in the scene",
#     lambda c: f"a photo of a small {c}.",
#     lambda c: f"a photo of a medium {c}.",
#     lambda c: f"a photo of a large {c}.",
#     lambda c: f"This is a photo of a small {c}.",
#     lambda c: f"This is a photo of a medium {c}.",
#     lambda c: f"This is a photo of a large {c}.",
#     lambda c: f"There is a small {c} in the scene.",
#     lambda c: f"There is a medium {c} in the scene.",
#     lambda c: f"There is a large {c} in the scene.",
#     ]

# openai_imagenet_template = [
#     lambda c: f"a photo of a {c} in the scene",
#     ]

# openai_imagenet_template = [
#     lambda c: f"a photo of a {c}.",
#     lambda c: f"This is a photo of a {c}",
#     lambda c: f"There is a {c} in the scene",
#     lambda c: f"There is the {c} in the scene",
#     lambda c: f"a photo of a {c} in the scene",
#     lambda c: f"a photo of a small {c}.",
#     lambda c: f"a photo of a medium {c}.",
#     lambda c: f"a photo of a large {c}.",
#     lambda c: f"This is a photo of a small {c}.",
#     lambda c: f"This is a photo of a medium {c}.",
#     lambda c: f"This is a photo of a large {c}.",
#     lambda c: f"There is a small {c} in the scene.",
#     lambda c: f"There is a medium {c} in the scene.",
#     lambda c: f"There is a large {c} in the scene.",
#     lambda c: f"a photo of the {c}.",
#     lambda c: f"This is a photo of the {c}",
#     lambda c: f"a photo of the {c} in the scene",
#     lambda c: f"a photo of the small {c}.",
#     lambda c: f"a photo of the medium {c}.",
#     lambda c: f"a photo of the large {c}.",
#     lambda c: f"This is a photo of the small {c}.",
#     lambda c: f"This is a photo of the medium {c}.",
#     lambda c: f"This is a photo of the large {c}.",
#     lambda c: f"There is the small {c} in the scene.",
#     lambda c: f"There is the medium {c} in the scene.",
#     lambda c: f"There is the large {c} in the scene.",
#     ]

# openai_imagenet_template = [
#     lambda c: f'a bad photo of a {c}.',
#     lambda c: f'a photo of many {c}.',
#     lambda c: f'a sculpture of a {c}.',
#     lambda c: f'a photo of the hard to see {c}.',
#     lambda c: f'a low resolution photo of the {c}.',
#     lambda c: f'a rendering of a {c}.',
#     lambda c: f'graffiti of a {c}.',
#     lambda c: f'a bad photo of the {c}.',
#     lambda c: f'a cropped photo of the {c}.',
#     lambda c: f'a tattoo of a {c}.',
#     lambda c: f'the embroidered {c}.',
#     lambda c: f'a photo of a hard to see {c}.',
#     lambda c: f'a bright photo of a {c}.',
#     lambda c: f'a photo of a clean {c}.',
#     lambda c: f'a photo of a dirty {c}.',
#     lambda c: f'a dark photo of the {c}.',
#     lambda c: f'a drawing of a {c}.',
#     lambda c: f'a photo of my {c}.',
#     lambda c: f'the plastic {c}.',
#     lambda c: f'a photo of the cool {c}.',
#     lambda c: f'a close-up photo of a {c}.',
#     lambda c: f'a black and white photo of the {c}.',
#     lambda c: f'a painting of the {c}.',
#     lambda c: f'a painting of a {c}.',
#     lambda c: f'a pixelated photo of the {c}.',
#     lambda c: f'a sculpture of the {c}.',
#     lambda c: f'a bright photo of the {c}.',
#     lambda c: f'a cropped photo of a {c}.',
#     lambda c: f'a plastic {c}.',
#     lambda c: f'a photo of the dirty {c}.',
#     lambda c: f'a jpeg corrupted photo of a {c}.',
#     lambda c: f'a blurry photo of the {c}.',
#     lambda c: f'a photo of the {c}.',
#     lambda c: f'a good photo of the {c}.',
#     lambda c: f'a rendering of the {c}.',
#     lambda c: f'a {c} in a video game.',
#     lambda c: f'a photo of one {c}.',
#     lambda c: f'a doodle of a {c}.',
#     lambda c: f'a close-up photo of the {c}.',
#     lambda c: f'a photo of a {c}.',
#     lambda c: f'the origami {c}.',
#     lambda c: f'the {c} in a video game.',
#     lambda c: f'a sketch of a {c}.',
#     lambda c: f'a doodle of the {c}.',
#     lambda c: f'a origami {c}.',
#     lambda c: f'a low resolution photo of a {c}.',
#     lambda c: f'the toy {c}.',
#     lambda c: f'a rendition of the {c}.',
#     lambda c: f'a photo of the clean {c}.',
#     lambda c: f'a photo of a large {c}.',
#     lambda c: f'a rendition of a {c}.',
#     lambda c: f'a photo of a nice {c}.',
#     lambda c: f'a photo of a weird {c}.',
#     lambda c: f'a blurry photo of a {c}.',
#     lambda c: f'a cartoon {c}.',
#     lambda c: f'art of a {c}.',
#     lambda c: f'a sketch of the {c}.',
#     lambda c: f'a embroidered {c}.',
#     lambda c: f'a pixelated photo of a {c}.',
#     lambda c: f'itap of the {c}.',
#     lambda c: f'a jpeg corrupted photo of the {c}.',
#     lambda c: f'a good photo of a {c}.',
#     lambda c: f'a plushie {c}.',
#     lambda c: f'a photo of the nice {c}.',
#     lambda c: f'a photo of the small {c}.',
#     lambda c: f'a photo of the weird {c}.',
#     lambda c: f'the cartoon {c}.',
#     lambda c: f'art of the {c}.',
#     lambda c: f'a drawing of the {c}.',
#     lambda c: f'a photo of the large {c}.',
#     lambda c: f'a black and white photo of a {c}.',
#     lambda c: f'the plushie {c}.',
#     lambda c: f'a dark photo of a {c}.',
#     lambda c: f'itap of a {c}.',
#     lambda c: f'graffiti of the {c}.',
#     lambda c: f'a toy {c}.',
#     lambda c: f'itap of my {c}.',
#     lambda c: f'a photo of a cool {c}.',
#     lambda c: f'a photo of a small {c}.',
#     lambda c: f'a tattoo of the {c}.',
# ]
